### ISSUE TITLE
Make Volume.intersections() arguments more flexible

### ISSUE THREAD

**Issue by NikDrummond** [clbarnes/ncollpyde#11]
* ncollpyde version:
* Python version:
* Operating System:

### Description

When you have a single origin and a single ray, the forced check on line 186 in main.py fails, when it should be allowed to pass. (elif here instead?)

It may also be worth thinking about expanding this so if a single source is given for multiple targets, rather than requiring a repeated array of source coords, a single source coord array (1x3) could be given.

### What I Did

```
coll.intersections(origin, ray_ends)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-84-cf0c8c6cbfae> in <module>
----> 1 coll.intersections(origin, ray_ends[0,0,:])

~/.local/lib/python3.8/site-packages/ncollpyde/main.py in intersections(self, src_points, tgt_points)
    185 
    186         if src.shape[1:] != (3,):
--> 187             raise ValueError("Points must be Nx3 array-like")
    188 
    189         idxs, points, bfs = self._impl.intersections(src.tolist(), tgt.tolist())

ValueError: Points must be Nx3 array-like
```

**Comment by NikDrummond** [comment]
example, not provided a mesh as the code doesn't get that far...

```target = np.array([732632.41589995, 222609.87059824, 234264.60556701])
source = np.array([731842.16012429, 222505.77426861, 234868.47621805])

coll.intersections(source, target)```

**Comment by clbarnes** [comment]
> When you have a single origin and a single ray, the forced check on line 186 in main.py fails, when it should be allowed to pass. (elif here instead?)

This was semi-intentional - in general I find inputs which are too flexible are harder to document and properly learn (even if they're easier to use the first time), so prefer to keep my interfaces doing just the one thing in cases where it's not difficult for the user to go down that one path (i.e. adding an extra `[]`).

My thinking is that the method returns some indices into the argument arrays: at present, those indices work transparently with both arguments. If the argument arrays are both 1D, what happens to those indices? If only one is 2D, how does the user (who may be working with abstracted variable names, deep in some software stack) know which one to index into?

The interface is also designed to encourage users down the route of best performance - that is, making many ray casts at once to minimise python-rust-python turnaround time.

> It may also be worth thinking about expanding this so if a single source is given for multiple targets, rather than requiring a repeated array of source coords, a single source coord array (1x3) could be given.

Yes, I was really tossing up between a few formats for this function's inputs.

1. `(starts, ends)`: like it is
2. `(starts, vectors)`: describing the ray rather than the end point
3. `(points, indices)`: list of all the points you're using, and then an Nx2 array of indices into the points array to describe each start and end point. That would mean you'd only have to give the location of the origin once, and then your `indices` array would look like `[[0, 1], [0, 2], [0, 3]]` - much more efficient

Each is most ergonomic for a particular use case. At the time I was thinking mainly of "where does a skeleton enter the mesh": that and the simplicity is why I went with the current implementation. If I were to add this, it'd probably be as a separate method, but it's unlikely to be a priority any time soon - probably best to just write a wrapper for it yourself (could be a subclass with the extra method which organises the arguments accordingly). Something like this would probably be enough:

```python
class VolumeExt(ncollpyde.Volume):
    def intersections_single_source(self, source, targets):
        return self.intersections([source] * len(targets), targets)
```

**Comment by NikDrummond** [comment]
Hey Chris, I'm still getting an error when I try to cast a ray between single points (see the example I gave)
